spring.application.name=employee-management

spring.datasource.url=jdbc:mysql://localhost:3306/employee_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=c2VjdXJlLWVtcC1tYW5hZ2VtZW50LWp3dC1zZWNyZXQta2V5LTIwMjYtbXVzdC1iZS1sb25n
app.jwt.expiration-ms=86400000